### ISSUE TITLE
Metddata.csv

### ISSUE THREAD

**Issue by SmarakPradhan** [anyvoiceai/Barkify#3]
Could you brief about the metadata.csv file that is required in the process.py?
I wanted to train bark for my own dataset

**Comment by anyvoiceai** [comment]
It's in the LJspeech dataset. You could download it at https://www.openslr.org

**Comment by SmarakPradhan** [comment]
How can I generate the metadata.csv for my own dataset?

**Comment by aartykov** [comment]
Hey, I have the same question as well. Could you generate metadata file for your custom dataset? @SmarakPradhan
