### ISSUE TITLE
长句子合成问题

### ISSUE THREAD

**Issue by flowspeech** [anyvoiceai/Barkify#4]
您好，我用单人版本数据进行训练，短句子合成没啥问题，只要句子字数变多，例如10字以上就会出现尾部发音模糊，或者叠音什么的，是由于参数没调好导致的，还是？

**Comment by anyvoiceai** [comment]
Maybe you could upload some samples or upload a checkpoint so that we could reproduce this senario?

**Comment by flowspeech** [comment]
[download.zip](https://github.com/anyvoiceai/Barkify/files/11595371/download.zip)
上面链接是合成例子，ckpt 太大，git 上上传不了，我网络都没变，只是codec 改用自己的2token 的版本，所以只有两个网络

**Comment by anyvoiceai** [comment]
主要原因是tokenizer有个小bug. 英文没有这个问题,我们后续会训练中文版本,如果你感兴趣可以加我们的QQ: 3284494602
